### PR TITLE
support PHP 8.1, drop 7.3

### LINKED ISSUE #14: Support PHP 8.1, drop 7.3
As far as I can see, Nextcloud 24 will support PHP 8.1 - at least the master branch has support for it: https://github.com/nextcloud/server/commit/72baee96988bbd9d3f7d68a90bf716008946000f

However, this composer package does not support PHP 8.1 yet. Please add support for it and publish it :-)

### PR DESCRIPTION
**Pull request by korelstar**
fixes #14

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]

**Comment by ChristophWurst** [comment]
https://packagist.org/packages/christophwurst/nextcloud#dev-master can now be used with 8.1

**Comment by nickvergessen** [comment]
This breaks testing in multi NC scenarios as you can not test latest dev-master if your composer file says platform 7.3 :(

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/twofactor_nextcloud_notification/runs/5357896377?check_suite_focus=true

**Comment by ChristophWurst** [comment]
See https://github.com/nextcloud/mail/pull/6066 for a "fix"

It's unfortunate, but also correct to enforce 7.3+ in this package.

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/mail/pull/6066/commits/f629d3a11b86f7e73d9d2f4ce4bc9794426e2875 is the relevant commit

**Comment by nickvergessen** [comment]
> It's unfortunate, but also correct to enforce 7.3+ in this package.

Yes. Let me use the workaround too for now.

**Pull request merged**
